version: "3"

services:
  ethermintdnode0:
    container_name: ethermintdnode0
    image: "ethermintd/node"
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "8545:8545"
      - "8546:8546"
    environment:
      - ID=0
      - LOG=${LOG:-ethermintd.log}
    volumes:
      - ./build:/ethermint:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2
    entrypoint: "bash start.sh"

  ethermintdnode1:
    container_name: ethermintdnode1
    image: "ethermintd/node"
    ports:
      - "26659-26660:26656-26657"
      - "1318:1317"
      - "8546:8545"
      - "8546:8546"
    environment:
      - ID=1
      - LOG=${LOG:-ethermintd.log}
    volumes:
      - ./build:/ethermint:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3
    entrypoint: "bash start.sh"

  ethermintdnode2:
    container_name: ethermintdnode2
    image: "ethermintd/node"
    environment:
      - ID=2
      - LOG=${LOG:-ethermintd.log}
    ports:
      - "26661-26662:26656-26657"
      - "1319:1317"
      - "8547:8545"
      - "8546:8546"
    volumes:
      - ./build:/ethermint:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4
    entrypoint: "bash start.sh"

  ethermintdnode3:
    container_name: ethermintdnode3
    image: "ethermintd/node"
    environment:
      - ID=3
      - LOG=${LOG:-ethermintd.log}
    ports:
      - "26663-26664:26656-26657"
      - "1320:1317"
      - "8548:8545"
      - "8546:8546"
    volumes:
      - ./build:/ethermint:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5
    entrypoint: "bash start.sh"

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16
