[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "=1.8.11"

[[constraint]]
  name = "github.com/cosmos/cosmos-sdk"
  version = "=0.24.2"

[[constraint]]
  name = "github.com/hashicorp/golang-lru"
  revision = "0fb14efe8c47ae851c0034ed7a448854d3d34cf3"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "~0.0.1"

[[override]]
  name = "github.com/tendermint/iavl"
  version = "=v0.9.2"

[[override]]
  name = "github.com/tendermint/tendermint"
  version = "=v0.23.1-rc0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "=1.2.1"

[[constraint]] 
  name = "github.com/pkg/errors"
  version = "=0.8.0"

[[override]]
  name = "gopkg.in/fatih/set.v0"
  version = "=0.1.0"

[prune]
  go-tests = true
