[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "=1.8.11"

[[constraint]]
  name = "github.com/cosmos/cosmos-sdk"
  version = "=0.21.0"

[[constraint]]
  name = "github.com/hashicorp/golang-lru"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "~0.0.1"

[[override]]
  name = "google.golang.org/genproto"
  revision = "7fd901a49ba6a7f87732eb344f6e3c5b19d1b200"

[[override]]
  name = "github.com/tendermint/tendermint"
  version = "=0.22.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "=1.2.2"

[prune]
  go-tests = true
