name: Documentation
# This job builds and deploys documenation to github pages.
# It runs on every push to main.
on:
  push:
    branches:
      - main
  schedule:
    - cron: "* 0 * * *"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: tendermintdev/docker-website-deployment
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          fetch-depth: 0
          repository: "tharsis/ethermint"

      - name: Install and Build ğŸ”§
        run: |
          apk add rsync
          make build-docs LEDGER_ENABLED=false

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ~/output